const express = require('express');
const getUsers = require('../controllers/UserController.js');
const getUserById = require('../controllers/UserController.js');
const createUser = require('../controllers/UserController.js');
const updateUser = require('../controllers/UserController.js');
const deleteUser = require('../controllers/UserController.js');
const getUsserByLoginAndPassword = require('../controllers/UserController.js');
const router = express.Router();
router.get('/users', getUsers);
router.get('/user/:id', getUserById);
router.post('/user', createUser);
router.patch('/user/:id', updateUser);
router.delete('/user/:id', deleteUser);
router.post("/userByLoginAndPass", getUsserByLoginAndPassword);